language: python

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - ./setup.py install
  - pip install --quiet --requirement examples/requirements.txt
  - pip install --quiet pylint

script:
  - python3 -m unittest --verbose
  - pylint nettirely.py examples

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - 'chat.freenode.net#8Banana'
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'
