language: python

python:
  - '3.6'
  - 'nightly'

sudo: false

cache: pip

install:
  - pip install .
  - pip install -r examples/requirements.txt
  - pip install pylint black

script:
  - python3 -m unittest --verbose
  - pylint nettirely.py examples
  - black --check .

notifications:
  email:
    on_success: change
    on_failure: change
  irc:
    channels:
      - 'chat.freenode.net#8Banana'
    skip_join: true
    on_success: change
    on_failure: always
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}'

matrix:
  allow_failures:
    - python: 'nightly'
